lib/exam_web/router.ex
defmodule ExamWeb.Router do
  use ExamWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExamWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/bookings", BookingController

  end

  # Other scopes may use custom stacks.
  # scope "/api", ExamWeb do
  #   pipe_through :api
  # end
end

lib/exam/application.ex
defmodule Exam.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Exam.Repo, []),
      # Start the endpoint when the application starts
      supervisor(ExamWeb.Endpoint, []),
      # Start your own worker by calling: Exam.Worker.start_link(arg1, arg2, arg3)
      # worker(Exam.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Exam.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ExamWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/exam/book/extension.ex
defmodule Exam.Book.Extention do
  use Ecto.Schema
  import Ecto.Changeset


  schema "extention" do
    field :title, :string
    field :code, :string
    field :start_date, :string
    field :due_date, :string
    field :times_extended, :string
    field :action, :string
    timestamps()
  end

  @doc false
  def changeset(extention, attrs) do
    extention
    |> cast(attrs, [:title, :code, :start_date, :due_date, :times_extended, :action])
    |> validate_required([:title, :code, :start_date, :due_date, :times_extended, :action])
  end
end

lib/exam/repo.ex
defmodule Exam.Repo do
  use Ecto.Repo, otp_app: :exam

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/exam_web/controllers/booking_controller.ex
defmodule ExamWeb.BookingController do
  use ExamWeb, :controller
  import Ecto.Query, only: [from: 2]
  alias Exam.Repo
  alias Exam.Exam, as: EXM

  def index(conn, _params) do
    query= from t in EXM, select: t
    exam = Repo.all(query)
    render conn, "index.html", exam: exam
  end
end

lib/exam_web/controllers/page_controller.ex
defmodule ExamWeb.PageController do
  use ExamWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/exam_web/views/booking_view.ex
defmodule ExamWeb.BookingView do
  use ExamWeb, :view
end

lib/exam_web/views/error_view.ex
defmodule ExamWeb.ErrorView do
  use ExamWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/exam_web/views/layout_view.ex
defmodule ExamWeb.LayoutView do
  use ExamWeb, :view
end

lib/exam_web/views/page_view.ex
defmodule ExamWeb.PageView do
  use ExamWeb, :view
end

lib/exam_web/templates/booking/index.html.eex
<template>
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<head>
<body>
<h1>My book loans</h1>
<div id="app">
  <ui-checkbox v-model="value" label="foo" name="foo"></ui-checkbox>
</div>

<ul>
  <li>
    <strong>Title:</strong>
    <%= @item.title %>
  </li>
  <li>
    <strong>Code:</strong>
    <%= @item.code %>
  </li>
  <li>
    <strong>Start date:</strong>
    <%= @item.start_date %>
  </li>
  <li>
    <strong>Due date:</strong>
    <%= @item.due_date %>
  </li>
  <li>
    <strong>Times extended:</strong>
    <%= @item.times_extended %>
  </li>
  <li>
    <div id="exam-app">
      <%= form_for @changeset, exam_path(@conn, :update, @item), fn item -> %>
        <div class="form-group">
            <button class="btn btn-default" v-on:click="extend" id="extend">Extend</button>
        </div>
      <% end %>
    </div>
  </li>
</ul>
<body>
<template>

lib/exam_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Exam!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/exam_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>